export const nameBand = ' LOS VIOLADORES ';
export let nameSongs = [
	"SENTIMIENTO FATAL", /*1*/
	"1, 2, ULTRAVIOLENTO", /*2*/
	"MÁS ALLÁ DEL BIEN Y EL MAL", /*3*/
	"FUERA DE SEKTOR", /*4*/
	"NADA NI NADIE NOS PUEDE DOBLEGAR", /*5*/
	"ESPERA Y VERAS", /*6*/
	"SIN ATADURAS", /*7*/
	"QUIERO SER YO, QUIERO SER LIBRE", /*8*/
	"REVOLUCIÓN INTER", /*9*/
	"COMUNICADO #166", /*10*/
	"BEAT AFRICANO", /*11*/
	"ZONA ROJA", /*12*/
	"EL ÚLTIMO HOMBRE", /*13*/
	"LA ERA DEL CORREGIDOR", /*14*/
	" EL CORREGIDOR", /*15*/
	"COMO LA PRIMERA VEZ", /*16*/
	"SOMOS LATINOAMERICA", /*17*/
	"ABURRIDO DIVERTIDO", /*18*/
	"MERCADO INDIO", /*19*/
	"SOLO UNA AGRESIÓN", /*20*/
]